include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    non_constant_identifier_names: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false